"""Add cancellation tracking fields

Revision ID: 4c0e23c19a5c
Revises: e04a9e556ef0
Create Date: 2025-07-08 03:05:57.563523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c0e23c19a5c'
down_revision = 'e04a9e556ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_reason', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cancellation_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'package', ['package_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancellation_notes')
        batch_op.drop_column('cancellation_reason')

    # ### end Alembic commands ###
