"""add payment fields

Revision ID: 6603467eefea
Revises: 83b0250f1a0f
Create Date: 2025-07-06 09:31:19.390259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6603467eefea'
down_revision = '83b0250f1a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('num_people', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['reference'])
        batch_op.drop_column('booking_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_date', mysql.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('phone',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('payment_reference')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('num_people')
        batch_op.drop_column('user_id')
        batch_op.drop_column('reference')

    # ### end Alembic commands ###
