"""Add booking_date and booking_time to Booking

Revision ID: 0a45b1eab94f
Revises: 4c0e23c19a5c
Create Date: 2025-07-08 21:32:56.661606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a45b1eab94f'
down_revision = '4c0e23c19a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('booking_time', sa.Time(), nullable=True))
        batch_op.create_foreign_key(None, 'package', ['package_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('booking_time')
        batch_op.drop_column('booking_date')

    # ### end Alembic commands ###
