"""add date_of_birth and bio to user

Revision ID: 0a800411dbb6
Revises: 693ea001bad7
Create Date: 2025-07-26 10:11:07.562060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a800411dbb6'
down_revision = '693ea001bad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'user' in existing_tables:
        with op.batch_alter_table('user', schema=None) as batch_op:
            user_columns = {col['name'] for col in inspector.get_columns('user')}
            if 'date_of_birth' not in user_columns:
                batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
            if 'bio' not in user_columns:
                batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'user' in existing_tables:
        with op.batch_alter_table('user', schema=None) as batch_op:
            user_columns = {col['name'] for col in inspector.get_columns('user')}
            if 'bio' in user_columns:
                batch_op.drop_column('bio')
            if 'date_of_birth' in user_columns:
                batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
