"""Add destination column to tour

Revision ID: 14636034cefc
Revises: 6b62d392a450
Create Date: 2025-07-08 17:12:38.377555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14636034cefc'
down_revision = '6b62d392a450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination', sa.String(length=100), nullable=False))
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('tour_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('destination_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('tour_ibfk_2'), 'destination', ['destination_id'], ['id'])
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('destination')

    # ### end Alembic commands ###
