"""Add order_tracking_id to Booking

Revision ID: 1b4fa2c39468
Revises: 798c2116a4d4
Create Date: 2025-07-12 05:57:46.897682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b4fa2c39468'
down_revision = '798c2116a4d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_tracking_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('num_people',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('booking_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('booking_time',
               existing_type=mysql.TIME(),
               nullable=False)
        batch_op.alter_column('payment_method',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('payment_status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.create_foreign_key(None, 'package', ['package_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('payment_status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('booking_time',
               existing_type=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('booking_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('num_people',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('order_tracking_id')

    # ### end Alembic commands ###
