"""Updated Booking model

Revision ID: 33e4476f651f
Revises: 14636034cefc
Create Date: 2025-07-13 13:45:31.173917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33e4476f651f'
down_revision = '14636034cefc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('reference', sa.String(length=36), nullable=False))  # Commented out: column already exists
        # batch_op.add_column(sa.Column('full_name', sa.String(length=200), nullable=False))  # Commented out: column already exists
        # batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))  # Commented out: column already exists
        # batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=False))  # Commented out: column already exists
        # batch_op.add_column(sa.Column('booking_date', sa.Date(), nullable=False))  # Commented out: column already exists
        # batch_op.add_column(sa.Column('booking_time', sa.Time(), nullable=True))  # Commented out: column already exists
        # batch_op.add_column(sa.Column('num_people', sa.Integer(), nullable=False))  # Commented out: column already exists
        # batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))  # Commented out: column already exists
        # batch_op.add_column(sa.Column('payment_reference', sa.String(length=100), nullable=True))  # Commented out: column already exists
        # batch_op.add_column(sa.Column('payment_details', sa.String(length=255), nullable=True))  # Commented out: column already exists
        # batch_op.add_column(sa.Column('order_tracking_id', sa.String(length=100), nullable=True))  # Commented out: column already exists
       #  batch_op.add_column(sa.Column('cancellation_reason', sa.String(length=50), nullable=True))
       #  batch_op.add_column(sa.Column('cancellation_notes', sa.Text(), nullable=True))
       #  batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('total_amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('payment_status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        # batch_op.drop_index(batch_op.f('booking_reference')) # Commented out: index may not exist in fresh DB
        batch_op.create_unique_constraint(None, ['reference'])
        # batch_op.drop_column('customer_email')  # Commented out: column may not exist in fresh DB
       #  batch_op.drop_column('customer_phone')
       #  batch_op.drop_column('booking_reference')
       #  batch_op.drop_column('customer_name')
       #  batch_op.drop_column('tour_date')
       #  batch_op.drop_column('participants')
       #  batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('participants', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tour_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('customer_name', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('booking_reference', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('customer_phone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('customer_email', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('booking_reference'), ['booking_reference'], unique=True)
        batch_op.alter_column('payment_status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancellation_notes')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('order_tracking_id')
        batch_op.drop_column('payment_details')
        batch_op.drop_column('payment_reference')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('num_people')
        batch_op.drop_column('booking_time')
        batch_op.drop_column('booking_date')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('full_name')
        batch_op.drop_column('reference')

    # ### end Alembic commands ###
