"""Ensure user_id foreign key on inquiries table

Revision ID: 33fb3c63df00
Revises: 68bcbbdefd38
Create Date: 2025-07-26 10:31:26.537149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33fb3c63df00'
down_revision = '68bcbbdefd38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'inquiries' in existing_tables:
        with op.batch_alter_table('inquiries', schema=None) as batch_op:
            inquiries_columns = {col['name'] for col in inspector.get_columns('inquiries')}
            if 'user_id' not in inquiries_columns:
                batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
            # Check if foreign key already exists
            inquiries_fks = {fk['constrained_columns'][0] for fk in inspector.get_foreign_keys('inquiries')}
            if 'user_id' not in inquiries_fks:
                batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    if 'user' in existing_tables:
        with op.batch_alter_table('user', schema=None) as batch_op:
            user_columns = {col['name'] for col in inspector.get_columns('user')}
            if 'otp_expiry' in user_columns:
                batch_op.drop_column('otp_expiry')
            if 'login_attempts' in user_columns:
                batch_op.drop_column('login_attempts')
            if 'otp_code' in user_columns:
                batch_op.drop_column('otp_code')
            if 'created_at' in user_columns:
                batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'user' in existing_tables:
        with op.batch_alter_table('user', schema=None) as batch_op:
            user_columns = {col['name'] for col in inspector.get_columns('user')}
            if 'created_at' not in user_columns:
                batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
            if 'otp_code' not in user_columns:
                batch_op.add_column(sa.Column('otp_code', mysql.VARCHAR(length=8), nullable=True))
            if 'login_attempts' not in user_columns:
                batch_op.add_column(sa.Column('login_attempts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
            if 'otp_expiry' not in user_columns:
                batch_op.add_column(sa.Column('otp_expiry', mysql.DATETIME(), nullable=True))

    if 'inquiries' in existing_tables:
        with op.batch_alter_table('inquiries', schema=None) as batch_op:
            inquiries_columns = {col['name'] for col in inspector.get_columns('inquiries')}
            if 'user_id' in inquiries_columns:
                batch_op.drop_constraint(None, type_='foreignkey')
                batch_op.drop_column('user_id')

    # ### end Alembic commands ###
