"""Add short_description to tour

Revision ID: 531ed7a66213
Revises: 144b19ab5fde
Create Date: 2025-07-18 15:16:49.554023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '531ed7a66213'
down_revision = '144b19ab5fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('available_spots', sa.Integer(), nullable=False),
    sa.Column('price_override', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_requests', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('order_tracking_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cancellation_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('reference',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.alter_column('booking_time',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('payment_details',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('duration_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('max_participants', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_participants', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('difficulty_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('departure_location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image_gallery', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('inclusions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('exclusions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('itinerary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('available_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('available_to', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('meta_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('tour_destination_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])
        batch_op.drop_column('max_capacity')
        batch_op.drop_column('destination_id')
        batch_op.drop_column('current_bookings')
        batch_op.drop_column('location')
        batch_op.drop_column('duration_hours')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_hours', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_bookings', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('destination_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('max_capacity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tour_destination_id_fkey'), 'destination', ['destination_id'], ['id'])
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('category_id')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('available_to')
        batch_op.drop_column('available_from')
        batch_op.drop_column('itinerary')
        batch_op.drop_column('exclusions')
        batch_op.drop_column('inclusions')
        batch_op.drop_column('image_gallery')
        batch_op.drop_column('image')
        batch_op.drop_column('departure_location')
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('min_participants')
        batch_op.drop_column('max_participants')
        batch_op.drop_column('duration_type')
        batch_op.drop_column('duration')
        batch_op.drop_column('short_description')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('payment_details',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('booking_time',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('reference',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancellation_notes')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('order_tracking_id')
        batch_op.drop_column('special_requests')

    op.drop_table('tour_date')
    # ### end Alembic commands ###
