"""Add payment fields to booking

Revision ID: 67305048430e
Revises: 0a45b1eab94f
Create Date: 2025-07-11 21:39:07.487482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67305048430e'
down_revision = '0a45b1eab94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_details', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'package', ['package_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('payment_details')

    # ### end Alembic commands ###
