"""Add settings fields to User model

Revision ID: 68bcbbdefd38
Revises: 0a800411dbb6
Create Date: 2025-07-26 10:22:32.131059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68bcbbdefd38'
down_revision = '0a800411dbb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_attempts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otp_expiry', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('otp_code', mysql.VARCHAR(length=8), nullable=True))
        batch_op.drop_column('date_created')
        batch_op.drop_column('public_profile')
        batch_op.drop_column('two_factor_auth')
        batch_op.drop_column('timezone')
        batch_op.drop_column('language')
        batch_op.drop_column('sms_notifications')
        batch_op.drop_column('newsletter')
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
