"""add phone to user

Revision ID: 693ea001bad7
Revises: d7047572fd3f
Create Date: 2025-07-26 09:41:36.081199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693ea001bad7'
down_revision = 'd7047572fd3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
