"""add phone to user

Revision ID: 693ea001bad7
Revises: d7047572fd3f
Create Date: 2025-07-26 09:41:36.081199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693ea001bad7'
down_revision = 'd7047572fd3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'user' in existing_tables:
        with op.batch_alter_table('user', schema=None) as batch_op:
            user_columns = {col['name'] for col in inspector.get_columns('user')}
            if 'phone' not in user_columns:
                batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'user' in existing_tables:
        with op.batch_alter_table('user', schema=None) as batch_op:
            user_columns = {col['name'] for col in inspector.get_columns('user')}
            if 'phone' in user_columns:
                batch_op.drop_column('phone')

    # ### end Alembic commands ###
