"""Add last_login to user

Revision ID: 995e75c4bda2
Revises: create_all_tables
Create Date: 2025-07-22 14:08:04.083152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '995e75c4bda2'
down_revision = 'create_all_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'booking' in existing_tables:
        with op.batch_alter_table('booking', schema=None) as batch_op:
            # Check if foreign keys already exist
            booking_fks = {fk['constrained_columns'][0] for fk in inspector.get_foreign_keys('booking')}
            if 'tour_id' not in booking_fks:
                batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'])
            if 'user_id' not in booking_fks:
                batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    if 'review' in existing_tables:
        with op.batch_alter_table('review', schema=None) as batch_op:
            review_fks = {fk['constrained_columns'][0] for fk in inspector.get_foreign_keys('review')}
            if 'tour_id' not in review_fks:
                batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'])
            if 'user_id' not in review_fks:
                batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    if 'tour' in existing_tables:
        with op.batch_alter_table('tour', schema=None) as batch_op:
            tour_fks = {fk['constrained_columns'][0] for fk in inspector.get_foreign_keys('tour')}
            if 'category_id' not in tour_fks:
                batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])

    if 'tour_date' in existing_tables:
        with op.batch_alter_table('tour_date', schema=None) as batch_op:
            tour_date_fks = {fk['constrained_columns'][0] for fk in inspector.get_foreign_keys('tour_date')}
            if 'tour_id' not in tour_date_fks:
                batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'])

    if 'tour_itinerary_day' in existing_tables:
        with op.batch_alter_table('tour_itinerary_day', schema=None) as batch_op:
            itinerary_fks = {fk['constrained_columns'][0] for fk in inspector.get_foreign_keys('tour_itinerary_day')}
            if 'tour_id' not in itinerary_fks:
                batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'])

    if 'user' in existing_tables:
        with op.batch_alter_table('user', schema=None) as batch_op:
            user_columns = {col['name'] for col in inspector.get_columns('user')}
            if 'last_login' not in user_columns:
                batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
            if 'login_attempts' not in user_columns:
                batch_op.add_column(sa.Column('login_attempts', sa.Integer(), nullable=True))
            if 'account_locked' not in user_columns:
                batch_op.add_column(sa.Column('account_locked', sa.Boolean(), nullable=True))
            # Only alter password_hash if it exists and is the old type
            if 'password_hash' in user_columns:
                batch_op.alter_column('password_hash',
                       existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=120),
                       type_=sa.String(length=255),
                       existing_nullable=False)

    if 'wishlist' in existing_tables:
        with op.batch_alter_table('wishlist', schema=None) as batch_op:
            wishlist_fks = {fk['constrained_columns'][0] for fk in inspector.get_foreign_keys('wishlist')}
            if 'tour_id' not in wishlist_fks:
                batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'])
            if 'user_id' not in wishlist_fks:
                batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=120),
               existing_nullable=False)
        batch_op.drop_column('account_locked')
        batch_op.drop_column('login_attempts')
        batch_op.drop_column('last_login')

    with op.batch_alter_table('tour_itinerary_day', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('tour_date', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
