"""Add last_login to user

Revision ID: 995e75c4bda2
Revises: d181f4666337
Create Date: 2025-07-22 14:08:04.083152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '995e75c4bda2'
down_revision = 'd181f4666337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])

    with op.batch_alter_table('tour_date', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'])

    with op.batch_alter_table('tour_itinerary_day', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('account_locked', sa.Boolean(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=120),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=120),
               existing_nullable=False)
        batch_op.drop_column('account_locked')
        batch_op.drop_column('login_attempts')
        batch_op.drop_column('last_login')

    with op.batch_alter_table('tour_itinerary_day', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('tour_date', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
