"""Initial clean migration

Revision ID: d181f4666337
Revises: 
Create Date: 2025-07-21 21:00:50.589033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd181f4666337'
down_revision = 'create_all_tables'  # Now runs AFTER create_all_tables
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop inquiry table if it exists (for migrations from older schema)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'inquiry' in existing_tables:
        op.drop_table('inquiry')
    
    # Only alter tables if they exist
    if 'booking' in existing_tables:
        with op.batch_alter_table('booking', schema=None) as batch_op:
            batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'])
            batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    if 'review' in existing_tables:
        with op.batch_alter_table('review', schema=None) as batch_op:
            batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'])
            batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    if 'tour' in existing_tables:
        with op.batch_alter_table('tour', schema=None) as batch_op:
            batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])

    if 'tour_date' in existing_tables:
        with op.batch_alter_table('tour_date', schema=None) as batch_op:
            batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'])

    if 'tour_itinerary_day' in existing_tables:
        with op.batch_alter_table('tour_itinerary_day', schema=None) as batch_op:
            batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'])

    if 'user' in existing_tables:
        with op.batch_alter_table('user', schema=None) as batch_op:
            # Check if columns already exist before adding
            user_columns = {col['name'] for col in inspector.get_columns('user')}
            if 'otp_code' not in user_columns:
                batch_op.add_column(sa.Column('otp_code', sa.String(length=8), nullable=True))
            if 'otp_expiry' not in user_columns:
                batch_op.add_column(sa.Column('otp_expiry', sa.DateTime(), nullable=True))

    if 'wishlist' in existing_tables:
        with op.batch_alter_table('wishlist', schema=None) as batch_op:
            batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
            batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_expiry')
        batch_op.drop_column('otp_code')

    with op.batch_alter_table('tour_itinerary_day', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('tour_date', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('inquiry',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('message', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('inquiry_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
