"""add first_name and last_name to user

Revision ID: d7047572fd3f
Revises: add_inquiry_table
Create Date: 2025-07-26 09:39:09.674332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7047572fd3f'
down_revision = 'add_inquiry_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'user' in existing_tables:
        with op.batch_alter_table('user', schema=None) as batch_op:
            user_columns = {col['name'] for col in inspector.get_columns('user')}
            if 'first_name' not in user_columns:
                batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=True))
            if 'last_name' not in user_columns:
                batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'user' in existing_tables:
        with op.batch_alter_table('user', schema=None) as batch_op:
            user_columns = {col['name'] for col in inspector.get_columns('user')}
            if 'last_name' in user_columns:
                batch_op.drop_column('last_name')
            if 'first_name' in user_columns:
                batch_op.drop_column('first_name')

    # ### end Alembic commands ###
