"""create packages table

Revision ID: e04a9e556ef0
Revises: 6603467eefea
Create Date: 2025-07-06 11:01:22.190193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e04a9e556ef0'
down_revision = '6603467eefea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_per_person', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key("fk_booking_package_id", 'package', ['package_id'], ['id'])
        batch_op.drop_column('tour_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint("fk_booking_package_id", type_='foreignkey')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('package_id')

    op.drop_table('package')
    # ### end Alembic commands ###
