"""Add reviews relationship

Revision ID: f92f5d48952a
Revises: 77ce3642259e
Create Date: 2025-07-13 22:15:46.533164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f92f5d48952a'
down_revision = '77ce3642259e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=100), nullable=False),
    sa.Column('reviewer_email', sa.String(length=120), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('reference',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('payment_status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('payment_details',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('cancellation_notes')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('order_tracking_id')
        batch_op.drop_column('cancellation_reason')

    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_bookings', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('duration_hours', sa.Integer(), nullable=True))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('meta_description')
        batch_op.drop_column('inclusions')
        batch_op.drop_column('duration_type')
        batch_op.drop_column('departure_location')
        batch_op.drop_column('min_participants')
        batch_op.drop_column('duration')
        batch_op.drop_column('category_id')
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('available_from')
        batch_op.drop_column('image_gallery')
        batch_op.drop_column('itinerary')
        batch_op.drop_column('meta_title')
        batch_op.drop_column('exclusions')
        batch_op.drop_column('available_to')
        batch_op.drop_column('featured_image')
        batch_op.drop_column('destination')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('short_description')
        batch_op.drop_column('max_participants')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_participants', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('short_description', mysql.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('is_featured', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('destination', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('featured_image', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('available_to', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('exclusions', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('meta_title', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('itinerary', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('image_gallery', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('available_from', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('difficulty_level', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('min_participants', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('departure_location', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('duration_type', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('inclusions', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('meta_description', mysql.VARCHAR(length=300), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('duration_hours')
        batch_op.drop_column('location')
        batch_op.drop_column('current_bookings')
        batch_op.drop_column('max_capacity')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_reason', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('order_tracking_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_notes', mysql.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('payment_details',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('payment_status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('payment_method',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('reference',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('updated_at')

    op.drop_table('review')
    op.drop_table('user')
    # ### end Alembic commands ###
