"""Add featured_image column to Tour

Revision ID: fa1db7a8598e
Revises: 7c511cc2fdfe
Create Date: 2025-07-18 12:22:22.338204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1db7a8598e'
down_revision = '7c511cc2fdfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_column('featured_image')

    # ### end Alembic commands ###
